project_id = "htgvtxuxhpisuphszfvu"

[functions.generate-script]
verify_jwt = false

[functions.enhance-script]
verify_jwt = true

[functions.generate-captions-hashtags]
verify_jwt = true

[functions.generate-voiceover]
verify_jwt = true

[functions.generate-visual-suggestions]
verify_jwt = true
